name: LXD Panel Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: chn-lee-yumi/lxd_cluster_panel
          
      #- name: Init LXD
      #  run: |
      #    lxd init < lxd_init.yml
      
      - name: Init Env
        run: |
          iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          iptables -I FORWARD -j ACCEPT
          pip3 install flask
          pip3 install flask_login
          nohup python3 main.py &
      
      - name: install cloudflare
        run: |
          cd /home/runner/tunnel
          aria2c "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
          sudo dpkg -i cloudflared-linux-amd64.deb
          nohup cloudflared tunnel --url 0.0.0.0:8080 &
          sleep 10
          cat nohup.out
          
      - name: enable debug interface
        uses: chn-lee-yumi/debugger-action@master
